ntpapp/urls.py
from django.urls import path
from .views import *


app_name = "ntpapp"
urlpatterns = [
    path('base_layout/', ClientBaseView.as_view(), name="clientbase"),
    path('get-blogs/', ClientGetBlogListView.as_view(), name="clientgetbloglist"),
    path('', ClientHomeView.as_view(), name="clienthome"),
    path('about/', ClientAboutView.as_view(), name="clientabout"),
    path('contact/', ClientContactView.as_view(), name="clientcontact"),

    path('our-blog/<int:pk>/detail/', ClientBlogDetailView.as_view(),
         name="clientblogdetail"),
    path('category/<int:pk>/detail/', ClientCategoryDetailView.as_view(),
         name="clientcategorydetail"),

    path('festival/', ClientFestivalListView.as_view(),
         name="clientfestivallist"),

    path('heritage/detail/',ClientHeritageListView.as_view(),
         name="clientheritagelist"),

    path('festival/<int:pk>/', ClientFestivalDetailView.as_view(),
         name="clientfestivaldetail"),

    path('gallary/', ClientGallaryListView.as_view(),
         name="clientgallarylist"),

    path('feed/', LatestEntriesFeed()),
    path('natural-beauty/', NaturalBeautyView.as_view(), name="naturalbeauty"),

]

ntpproject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ntpapp.urls')),
    path('summernote/', include('django_summernote.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ntpapp/models.py
from django.contrib.auth.models import User
from django.db import models
from .constants import *


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        abstract = True


class ImageSlider(TimeStamp):
    image = models.ImageField(upload_to="sliders")
    title = models.CharField(max_length=200)
    details = models.CharField(max_length=500)

    def __str__(self):
        return self.title


class Category(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to="category")

    def __str__(self):
        return self.title


class Blog(TimeStamp):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="blogs")
    video_link = models.CharField(max_length=500, null=True, blank=True)
    details = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    view_count = models.PositiveIntegerField()

    def __str__(self):
        return self.title


class Festival(TimeStamp):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to="festivals")
    month = models.CharField(max_length=50, choices=MONTHS)
    day = models.CharField(max_length=50, choices=DAYS)
    duration = models.PositiveIntegerField(default=1)
    video_link = models.CharField(max_length=500, null=True, blank=True)
    details = models.TextField()
    significance = models.TextField()

    def __str__(self):
        return self.title

HERITAGE_TYPE = (
    ('Natural Beauty', 'Natural Beauty'),
    ('Cultural Heritage', 'Cultural Heritage'),
)

class Heritage(TimeStamp):
    title = models.CharField(max_length=200)
    heritage_type = models.CharField(max_length=200, choices=HERITAGE_TYPE)
    image = models.ImageField(upload_to="cuturalheritages")
    video_link = models.CharField(max_length=500, null=True, blank=True)
    location = models.CharField(max_length=30)
    significance = models.TextField()
    details = models.TextField()

    def __str__(self):
        return self.title

class Gallary(TimeStamp):
    title = models.CharField(max_length=20)
    image = models.ImageField(upload_to="gallarys")

    def __str__(self):
        return self.title



class ClientContact(TimeStamp):

    def __str__(self):
        return self.title

ntpapp/forms.py
from django import forms
from .models import *

ntpapp/views.py
from django.contrib.syndication.views import Feed
from django.urls import reverse, reverse_lazy
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from django.views.generic import *
from .models import *
from .forms import *


class ClientMixin(object):
    def get_context_data(self, **kwargs):
        print("It should be just after middleware")
        context = super().get_context_data(**kwargs)
        context['allcategory'] = Category.objects.all()
        context['allblogs'] = Blog.objects.order_by('-id')

        return context


class ClientGetBlogListView(View):
    def get(self, request, *args, **kwargs):
        blogs = Blog.objects.order_by('-id')
        jsondata = serializers.serialize('json', blogs)
        return HttpResponse(jsondata)


class ClientFestivalListView(ListView):
    template_name = "clienttemplates/clientfestivallist.html"
    queryset = Festival.objects.all()
    context_object_name = "festivals"


class ClientFestivalDetailView(DetailView):
    template_name = "clienttemplates/clientfestivaldetail.html"
    queryset = Festival.objects.all()
    context_object_name = "festival"


class ClientHeritageListView(ListView):
    template_name = "clienttemplates/clientheritagelist.html,clientfestivaldetail.html"
    queryset = Heritage.objects.all()
    context_object_name = "Heritage"



class ClientHeritageDetailView(DetailView):
    template_name = "clienttemplates/clientheritagedetail.html"
    queryset = Heritage.objects.all()
    context_object_name = "Heritage"





class ClientBaseView(ClientMixin, TemplateView):
    template_name = "clienttemplates/clientbase.html"


class ClientHomeView(ClientMixin, TemplateView):
    template_name = "clienttemplates/clienthome.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sliders'] = ImageSlider.objects.all()
        context['blogs'] = Blog.objects.order_by('-id')
        context['categorys'] = Category.objects.order_by('-id')
        return context


class ClientAboutView(ClientMixin, TemplateView):
    template_name = "clienttemplates/clientabout.html"


class ClientContactView(ClientMixin, TemplateView):
    template_name = "clienttemplates/clientContact.html"


class ClientBlogDetailView(ClientMixin, DetailView):
    template_name = "clienttemplates/clientblogdetail.html"
    model = Blog
    context_object_name = "blog"


class ClientGallaryListView(ClientMixin, ListView):
    template_name = "clienttemplates/clientgallarylist.html"
    model = Gallary
    context_object_name = "gallary"


class ClientCategoryDetailView(ClientMixin, DetailView):
    template_name = "clienttemplates/clientcategorydetail.html"
    # model = Category
    queryset = Category.objects.all()
    # queryset = Heritage.objects.filter(heritage_type="Natural Beauty")
    context_object_name = "category"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.exclude(id=self.object.id)
        return context


class LatestEntriesFeed(Feed):
    title = "Police beat site news"
    link = "/feed/"
    description = "Updates on changes and additions to police beat central."

    def items(self):
        return Blog.objects.order_by('-id')[:5]

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        return item.details

    # item_link is only needed if NewsItem has no get_absolute_url method.
    def item_link(self, item):
        return reverse('ntpapp:clientblogdetail', args=[item.pk])


class NaturalBeautyView(ClientMixin, TemplateView):
    template_name = "clienttemplates/naturalbeauty.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['naturalbeautys'] = Heritage.objects.filter(heritage_type="Natural Beauty")
        return context

templates/clienttemplates/clientabout.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}{% endblock %}
{% block clientabout %}active{% endblock %}

{% block css %}

{% endblock %}

{% block content  %}
<head><h1><b>About 	Us </b></h1></head>
<body>
 <div class="container">

          <p><span><i class="#" aria-hidden="true"></i></span> <h1>Visit Nepal  Tours and travel</h1> </p><br><br><br>

           <p>Visit Nepal is one of the leading tours and travel company of Nepal. It is a government registered travel agency which is recognized by Trekking Agencies' Association of Nepal. It is a client-oriented organization which was established in 20019 with a sole objective “Satisfied Customer Our Assets”. The organization has been providing the wide range of trek and tour services to thousands of tourists since then. The reviews of our customers’ speak aloud about us keeping NTA different from the crowd of trekking agencies. </p><br><br><br><br>


 <p><B>Motto:</B> Satisfied Customer Our Assets<br><br><br><br>


 <B>Vision:</B> Marketing Nepal’s beauty throughout the world<br><br><br><br>


<B>Mission:</B> Encourage international and domestic tourists and retain the country’s youth by creating job opportunities in the country<br><br><br>

<B>Core Values:</B> Provide genuine service through local guides focusing safety and salient trek without hampering local culture and natural existence. For further queries, please click contact us, as we are always ready for your service.
</p>



  </div>



{% endblock %}

{% block js %}

{% endblock %}

templates/clienttemplates/clientbase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>{% block title %}{% endblock %}</title>    
<link rel="shortcut icon" href="{% static 'clientstatic/images/arrows.png' %}" type="image/x-icon">

<link href="{% static 'clientstatic/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" media="all" /><!-- fontawesome -->     
<link href="{% static 'clientstatic/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" media="all" /><!-- Bootstrap stylesheet -->
<link href="{% static 'clientstatic/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="{% static 'clientstatic/css/flexslider.css' %}" type="text/css" media="screen" property="" />
<!-- stylesheet -->
<!-- meta tags -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- //meta tags -->
<!--fonts-->
<link href="//fonts.googleapis.com/css?family=Roboto+Condensed:300,300i,400,400i,700,700i&subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
<link href="//fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
<!--//fonts-->
<script type="text/javascript" src="{% static 'clientstatic/js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'clientstatic/js/main.js' %}"></script>
<!-- Required-js -->
<!-- main slider-banner -->
<script src="{% static 'clientstatic/js/skdslider.min.js' %}"></script>
<link href="{% static 'clientstatic/css/skdslider.css' %}" rel="stylesheet">
<script type="text/javascript">
		jQuery(document).ready(function(){
			jQuery('#demo1').skdslider({'delay':5000, 'animationSpeed': 2000,'showNextPrev':true,'showPlayButton':true,'autoSlide':true,'animationType':'fading'});
						
			jQuery('#responsive').change(function(){
			  $('#responsive_wrapper').width(jQuery(this).val());
			});
			
		});
</script>	
<!-- //main slider-banner --> 
<!-- start-smoth-scrolling -->
<script type="text/javascript" src="{% static 'clientstatic/js/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'clientstatic/js/easing.js' %}"></script>
<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".scroll").click(function(event){		
			event.preventDefault();
			$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
		});
	});
</script>
<!-- start-smoth-scrolling -->

<!-- scriptfor smooth drop down-nav -->
<script>
$(document).ready(function(){
    $(".dropdown").hover(            
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');        
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');       
        }
    );
});
</script>
<!-- //script for smooth drop down-nav -->
</head>
<body >
	<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v4.0"></script>
	<div id="fb-root"></div>
<script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v4.0"></script>
<!-- header -->
	<header>
		<div class="w3layouts-top-strip">
			<div class="container">
				<div class="logo">
					<h1><a href="{% url 'ntpapp:clienthome' %}">Visit Nepal </a></h1>
					<p>Naturally and Culturally</p>
				</div>
				<div class="w3ls-social-icons">
					<a class="facebook" href="//facebook.com"><i class="fa fa-facebook"></i></a>
					<a class="twitter" href="//twitter.com"><i class="fa fa-twitter"></i></a>
					<a class="youtube" href="//youtube.com"><i class="fa fa-rss"></i></a>
				</div>
			</div>
		</div>
		<!-- navigation -->
			<nav class="navbar navbar-default">
			  <div class="container">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
				  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				  </button>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				  <ul class="nav navbar-nav">
					<li><a class="{% block clienthome %}{% endblock %}" href="{% url 'ntpapp:clienthome' %}">Home</a></li>
					<li class="dropdown">
					  <a href="" class="{% block clientblog %}{% endblock %} dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Blogs <span class="caret"></span></a>
					  <ul class="dropdown-menu">
					  	{% for category in allcategory %}
						  <li><a href="{% url 'ntpapp:clientcategorydetail' category.id %}">{{category.title}}</a></li>
						{% endfor %}
						
					  </ul>
					</li>
					
					<li><a class="{% block clientfestivallist %}{% endblock %}" href="{% url 'ntpapp:clientfestivallist' %}">Festival/Events</a></li>
					<li class="dropdown">
					  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Heritage <span class="caret"></span></a>
					  <ul class="dropdown-menu">
					  <li><a href="{% url 'ntpapp:naturalbeauty' %}">Natural Beauty</a></li>
						<li><a href="//facebook.com">Cultural Heritage</a></li>
						
					  </ul>
					</li>
					<li><a class="{% block clientgallarylist %}{% endblock %}" href="{% url 'ntpapp:clientgallarylist' %}">Gallary</a></li>
					<li><a class="{% block clientabout %}{% endblock %}" href="{% url 'ntpapp:clientabout' %}">About</a></li>

					<li><a class="{% block clientcontact %}{% endblock %}" href="{% url 'ntpapp:clientcontact' %}">Contact</a></li>
				  </ul>
				</div><!-- /.navbar-collapse -->
				<div class="w3_agile_login">
							<div class="cd-main-header">
								<a class="cd-search-trigger" href="#cd-search"> <span></span></a>
								<!-- cd-header-buttons -->
							</div>
 
							</div>
						</div>
						<div class="clearfix"> </div>

			  </div><!-- /.container-fluid -->
			</nav>
			
		<!-- //navigation -->
	</header>
	<!-- //header -->

	{% block content %}


	{% endblock %}

	<div class="row">
		<div class="col-md-4" id="offlinedata">
			
		</div>
	</div>
	<!-- footer -->
	<div class="footer-agile-info">
		<div class="container">
			<div class="col-md-4 w3layouts-footer">
				<h3>Contact Information</h3>
					<p><span><i class="fa fa-map-marker" aria-hidden="true"></i></span>Sathdobato  lalitpur , Nepal </p>
					<p><span><i class="fa fa-envelope" aria-hidden="true"></i></span><a href="#">shankarsachin.com</a> </p>
					<p><span><i class="fa fa-mobile" aria-hidden="true"></i></span>P: +9779840894609 / +977 9861118242 </p>
					<p><span><i class="fa fa-globe" aria-hidden="true"></i></span><a href="#">W:Cosmos college of Management and technology </a></p>
			</div>
			 
 
		</div>
	</div>
	<!-- footer -->
	<!-- copyright -->
	<div class="copyright">
		<div class="container">
			<div class="w3agile-list">
				<ul>
					<li><a href="//clienthome.html">Home</a></li>
					<li><a href="//clientabout.html">About</a></li>
					<li><a href="photography.html">Photography</a></li>
					<li><a href="//clientcontact.html">Contact</a></li>
				</ul>
			</div>
			<div class="agileinfo">
				<p> Design by <a href="http://cosmoscollege.edu.np/">Sher|Prakash|Shankar|Bishoj</a></p>
			</div>
		</div>
	</div>
<!-- //copyright -->
<!-- here stars scrolling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
				};
			*/
								
			$().UItoTop({ easingType: 'easeOutQuart' });
								
			});
	</script>
<!-- //here ends scrolling icon -->

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'clientstatic/js/bootstrap.js' %}"></script>

<script type="text/javascript" src="{% static 'clientstatic/js/idb.js' %}"></script>
  <script type="text/javascript" src="{% static 'clientstatic/js/idbop.js' %}"></script>
</body>
</html>

templates/clienttemplates/clientcategorydetail.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}{% endblock %}
{% block clientblog %}active{% endblock %}

{% block css %}

{% endblock %}

{% block content %}
<div class="agile-banner">
	</div>
	<!-- //banner -->
	<!-- breadcrumbs -->
	<div class="breadcrumbs">
		<div class="container">
			<ol class="breadcrumb breadcrumb1 animated wow slideInLeft" data-wow-delay=".5s">
				<li><a href="index.html">Home</a></li>
				<li class="active">{{category.title}}</li>
			</ol>
		</div>
	</div>
<!-- //breadcrumbs -->
	<div class="container">
		<div class="banner-btm-agile">
			
		<!-- //btm-wthree-left -->
			<div class="col-md-9 btm-wthree-left">
			<div class="agileits_heading_section">
				<h3 class="wthree_head">{{category.title}}</h3>
				<p class="agileinfo_para">This is Nepal</p>
			</div>
				<div class="events w3">
					<div class="events-main">
						{% for blog in category.blog_set.all %}
						{% if forloop.counter|divisibleby:2 %}
						<div class="events-top">	
							<div class="col-md-6  w3ls fea-left">
								<div class="w3agile_special_deals_grid_left_grid">
									<a href="{% url 'ntpapp:clientblogdetail' blog.id  %}"><img src="{{blog.image.url}}" class="img-responsive" alt="" /></a>
								</div>
							</div>
							<div class="col-md-6 wthree fea-right">
								<h3>{{blog.title}}</h3>
								<p>{{blog.details|striptags|safe|truncatewords:"50"}}</p>
								<a class="agileits w3layouts" href="{% url 'ntpapp:clientblogdetail' blog.id  %}">Read More <span class="glyphicon agileits w3layouts glyphicon-arrow-right" aria-hidden="true"></span></a>
							</div>
							<div class="clearfix"> </div>
						</div>
						{% else %}
						<div class="events-top">
							<div class="col-md-6  w3-agile fea-right">
								<h3>{{blog.title}}</h3>
								<p>{{blog.details|striptags|safe|truncatewords:"50"}}</p>
								<a class="agileits w3layouts" href="{% url 'ntpapp:clientblogdetail' blog.id  %}">Read More <span class="glyphicon agileits w3layouts glyphicon-arrow-right" aria-hidden="true"></span></a>
							</div>
							<div class="col-md-6  fea-left">
								<div class="w3agile_special_deals_grid_left_grid">
									<a href="{% url 'ntpapp:clientblogdetail' blog.id  %}"><img src="{{blog.image.url}}" class="img-responsive" alt="" /></a>
								</div>
							</div>
								<div class="clearfix"> </div>
						</div>
						{% endif %}
						{% endfor %}
					</div>
				
				</div>	
			</div>
			<!-- //btm-wthree-left -->
				<!-- btm-wthree-right -->
			<div class="col-md-3 w3agile_blog_left">
				
				<div class="agileinfo_calender">
				<h3>CONNECT SOCIALLY</h3>
				<div class="w3ls-social-icons-1">
					<a class="pinterest" href="//pinterest.com"><i class="fa fa-pinterest-p"></i></a>
					<a class="linkedin" href="//linkedin.com"><i class="fa fa-linkedin"></i></a>
					<a class="google-plus" href="google-plus.com//"><i class="fa fa-google-plus"></i></a>
					<a class="youtub" href="//youtube.com"><i class="fa fa-behance"></i></a>
				</div>
				</div>
				<div class="w3ls_popular_posts">
					<div class="w3ls_popular_posts">
					<h3>Popular Posts</h3>
					<div class="agileits_popular_posts_grid">
						<div class="w3agile_special_deals_grid_left_grid">
							<a href="singlepage.html"><img src="{% static 'clientstatic/images/p1.jpg' %}" class="img-responsive" alt="" /></a>
						</div>
						<h4><a href="singlepage.html"></a>Waterfall in Nepal</h4>
						<h5><i class="fa fa-calendar" aria-hidden="true"></i>FEB 15,2019</h5>
					</div>
					<div class="agileits_popular_posts_grid">
						<div class="w3agile_special_deals_grid_left_grid">
								<a href="singlepage.html"><img src="{% static 'clientstatic/images/p2.jpg' %}" class="img-responsive" alt="" /></a>
							</div>
						<h4><a href="mounterring.com">Mountaring in Nepal</a></h4>
						<h5><i class="fa fa-calendar" aria-hidden="true"></i>FEB 15,2019</h5>
					</div>
					<div class="agileits_popular_posts_grid">
						<div class="w3agile_special_deals_grid_left_grid">
								<a href="singlepage.html"><img src="{% static 'clientstatic/images/p3.jpg' %}" class="img-responsive" alt="" /></a>
						</div>
						<h4><a href="singlepage.html"></a>wildlife reservation</h4>
						<h5><i class="fa fa-calendar" aria-hidden="true"></i>FEB 15,2017</h5>
					</div>
				</div>
				
				<div class="w3l_categories">
					<h3>Categories</h3>
					<ul>
						{% for cat in categories %}
						<li><a href="{% url 'ntpapp:clientcategorydetail' cat.id %}"><span class="glyphicon glyphicon-arrow-right" aria-hidden="true"></span>{{cat.title}}</a></li>
						{% endfor %}
						
					</ul>
				</div>
			<div class="w3ls_recent_posts">
					<h3>Recent Posts</h3>
					<div class="agileits_recent_posts_grid">
						<div class="agileits_recent_posts_gridl">
							<div class="w3agile_special_deals_grid_left_grid">
									<a href="singlepage.html"><img src="{% static 'clientstatic/images/r1.jpg' %}" class="img-responsive" alt="" /></a>
								</div>
						</div>
						<div class="agileits_recent_posts_gridr">
							<h4><a href="singlepage.html">Pokhara and its beauty</a></h4>
							<h5><i class="fa fa-calendar" aria-hidden="true"></i>FEB 15,2019</h5>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="agileits_recent_posts_grid">
						<div class="agileits_recent_posts_gridl">
							<div class="w3agile_special_deals_grid_left_grid">
									<a href="singlepage.html"><img src="{% static 'clientstatic/images/r2.jpg' %}" class="img-responsive" alt="" /></a>
								</div>
						</div>
						<div class="agileits_recent_posts_gridr">
							<h4><a href="singlepage.html">poonhill and its sunrising </a></h4>
							<h5><i class="fa fa-calendar" aria-hidden="true"></i>FEB 15,2019</h5>
						</div>
						<div class="clearfix"> </div>
					</div>
					<div class="agileits_recent_posts_grid">
						<div class="agileits_recent_posts_gridl">
							<div class="w3agile_special_deals_grid_left_grid">
									<a href="singlepage.html"><img src="{% static 'clientstatic/images/r3.jpg' %}" class="img-responsive" alt="" /></a>
								</div>
						</div>
						<div class="agileits_recent_posts_gridr">
							<h4><a href="singlepage.html">Lord buddha and lumbini </a></h4>
							<h5><i class="fa fa-calendar" aria-hidden="true"></i>FEB 15,2019</h5>
						</div>
						<div class="clearfix"> </div>
					</div>
				</div>
			<div class="w3l_tags">
					<h3>Tags</h3>
					<ul class="tag">
						<li><a href="singlepage.html">Photography</a></li>
						<li><a href="singlepage.html">Restaurant</a></li>
					</ul>
				</div>
			</div>
			<!-- //btm-wthree-right -->
			<div class="clearfix"></div>
		</div>
	</div>
</div>
{% endblock %}

templates/clienttemplates/clientfestivallist.html
{% extends 'clienttemplates/clientbase.html' %}

{% block festivallist %}active{% endblock %}


{% block content %}
<div class="container my-3">
	
<h3>All Festivals</h3>
<hr>
<div class="row">
	{% for festival in festivals %}
		<div class="col-md-4">
			<h4><a href="{% url 'ntpapp:clientfestivaldetail' festival.id %}">{{festival.title}} Festival(Month of Celebration: {{festival.month}})</a></h4><hr>
			<a href="{% url 'ntpapp:clientfestivaldetail' festival.id %}"><img src="{{festival.image.url}}" class="img-responsive img-thumbnail"></a><br>
			<h5>Significance: {{festival.significance|truncatechars:"100"}}</h5>
		</div>
	{% endfor %}
</div>
</div>


{% endblock %}

templates/clienttemplates/naturalbeauty.html
{% extends 'clienttemplates/clientbase.html' %}

{% block content %}

<h3>Natural Beauty</h3>

{% for h in naturalbeautys %}
<li>{{h.title}}</li>
{{h.details|safe}}
{% endfor %}
{% endblock %}